import {useState}  from "react";
import Head from "next/head";
import SearchBar from "~/components/searchBar";
import Coinslist from "~/components/coinsList";

export default function Home({ coins }) {
  const [filteredCoins, setFilteredCoins] = useState(coins);

  const handleChange = (e) => {
    e.preventDefault();
    let searchInput = e.target.value.toLowerCase();

    setFilteredCoins(
      coins.filter((coin) =>
        coin.name.toLowerCase().includes(searchInput.toLowerCase())
      )
    )
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="coin_app">
        <SearchBar change={handleChange} />
        <Coinslist filteredCoins={filteredCoins} />
      </div>
    </div>
  );
}


export const getStaticProps = async () => {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=10&page=1&sparkline=false"
  );

  const coins = await res.json();

  return {
    props: {
      coins,
    },
  };
};

//Material Ui https://mui.com
